### ISSUE TITLE
'desired_range' is not working, 'permitted_range' returns value out of the range, flexibility of 'permitted_range'

### ISSUE THREAD

**Issue by HengQuan1997** [interpretml/DiCE#106] opened 2021-03-11 12:32 UTC
Hi, I have the three questions.

Firstly, I get this error when I try to use 'desired_range'. 

![Desired_Range_Error](https://user-images.githubusercontent.com/68982226/110787753-b522b780-82a8-11eb-9fcb-347cc91398bd.JPG)

Secondly, sometimes permitted_range cannot ensure the  controlled feature is in the range. For instance, the second image shows that the age is not in the range of 23 and 24.

Lastly, it seems that I have to **set the range all for continuous features when using 'permitted_range'**. For instance, in the second image I have to **control another continuous feature 'hours_per_week**' although I **only want to control the 'age' feature.**
Otherwise, I will get a key error because I only control one continuous feature-**'age**'.
How can I only control one continuous feature by DICE?

![Image2_Permitted_Range](https://user-images.githubusercontent.com/68982226/110787904-e1d6cf00-82a8-11eb-9216-1e81234c12ef.JPG)

Thank you very much

**Comment by gaugup** [comment] 2021-03-12 05:17
@HengQuan1997  in my understanding desired_range should be used only for regression problems and desired_class should be used only in case of classification problems. You shouldn't set both. @amit-sharma  is that understanding correct?

**Comment by HengQuan1997** [comment] 2021-03-15 01:29
> @HengQuan1997 in my understanding desired_range should be used only for regression problems and desired_class should be used only in case of classification problems. You shouldn't set both. @amit-sharma is that understanding correct?

Hi @gaugup 

Thank you for the reply. You are correct regarding the 'desired range' function. desired_range should be used only for regression problems.

**Comment by gaugup** [comment] 2021-03-16 04:00
@HengQuan1997, for the second and the third scenario could you share the sample code/notebook?

**Comment by amit-sharma** [comment] 2021-03-16 05:49
@HengQuan1997 can you also confirm the version of DiCE you are using? The third issue might be due to using an earlier version---the latest version is 0.5.

**Comment by HengQuan1997** [comment] 2021-03-19 00:43
> @HengQuan1997 can you also confirm the version of DiCE you are using? The third issue might be due to using an earlier version---the latest version is 0.5.

Hi, You are correct. I think that I did not use the latest version of 0.5.

**Comment by gaugup** [comment] 2021-03-24 02:46
@HengQuan1997 are all your questions answered or are you still facing trouble using dice-ml? If your questions have been answered, then maybe we can close this issue.

**Comment by gaugup** [comment] 2021-12-28 00:53
Closing this issue due to no activity.

**Closed** 2021-12-28 00:54 UTC
